'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useParams, usePathname, useRouter } from 'next/navigation';
import { ArrowRight, CalendarClock, History, KeyRound, Loader2, LogOut, Mail, Phone, QrCode, Ticket, User } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';

type Props={onViewHistory?:()=>void;onViewCoupons?:()=>void};
export default function CustomerProfileV3({onViewHistory,onViewCoupons}:Props){
 const params=useParams();const pathname=usePathname();const router=useRouter();const slug=String(params.mitraSlug||'');const parts=pathname.split('/').filter(Boolean);const pi=parts.lastIndexOf('profile');const branch=pi>=2?parts[pi-1]:undefined;const base=branch?`/${slug}/${branch}`:`/${slug}`;
 const [loading,setLoading]=useState(true);const [user,setUser]=useState<any>(null);const [mode,setMode]=useState<'login'|'register'>('login');const [busy,setBusy]=useState(false);const [err,setErr]=useState('');const [login,setLogin]=useState({email:'',password:''});const [reg,setReg]=useState({name:'',email:'',phone:'',password:'',confirm:''});const [qr,setQr]=useState(false);
 useEffect(()=>{let live=true;(async()=>{try{const q=new URLSearchParams({slug});if(branch)q.set('branch_slug',branch);const r=await fetch(`/api/auth/me?${q}`,{credentials:'include',cache:'no-store'});const j=await r.json();if(live&&r.ok&&j.success)setUser(j.user)}catch{}finally{if(live)setLoading(false)}})();return()=>{live=false}},[slug,branch]);
 async function doLogin(e:FormEvent){e.preventDefault();setBusy(true);setErr('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:login.email.trim(),password:login.password,slug})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Login gagal');window.location.reload()}catch(e){setErr(e instanceof Error?e.message:'Login gagal')}finally{setBusy(false)}}
 async function doRegister(e:FormEvent){e.preventDefault();setErr('');if(reg.password!==reg.confirm){setErr('Konfirmasi password tidak cocok.');return}setBusy(true);try{const r=await fetch('/api/auth/customer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:reg.name.trim(),email:reg.email.trim(),phone:reg.phone.trim(),password:reg.password,slug})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Pendaftaran gagal');setMode('login');setLogin({email:reg.email,password:''})}catch(e){setErr(e instanceof Error?e.message:'Pendaftaran gagal')}finally{setBusy(false)}}
 async function logout(){try{await fetch('/api/auth/logout',{method:'POST'})}finally{router.replace(`${base}/profile`);router.refresh();window.location.reload()}}
 if(loading)return <div className="flex min-h-[70dvh] items-center justify-center bg-stone-50"><Loader2 className="h-6 w-6 animate-spin"/></div>;
 if(!user)return <div className="min-h-full bg-stone-50 px-4 pb-32 pt-7"><p className="text-[9px] font-black uppercase tracking-[.2em] text-black/30">KALOO account</p><h1 className="mt-2 text-[40px] font-black leading-[.92] tracking-[-.065em]">{mode==='login'?'Welcome back.':'Join the table.'}</h1>
  <div className="mt-8 flex rounded-full bg-stone-200 p-1"><button onClick={()=>{setMode('login');setErr('')}} className={`flex-1 rounded-full py-2.5 text-[9px] font-black uppercase tracking-[.13em] ${mode==='login'?'bg-black text-white':''}`}>Sign in</button><button onClick={()=>{setMode('register');setErr('')}} className={`flex-1 rounded-full py-2.5 text-[9px] font-black uppercase tracking-[.13em] ${mode==='register'?'bg-black text-white':''}`}>Create account</button></div>
  <form onSubmit={mode==='login'?doLogin:doRegister} className="mt-6 space-y-3">{mode==='register'&&<input required placeholder="Full name" value={reg.name} onChange={e=>setReg({...reg,name:e.target.value})} className="h-14 w-full rounded-2xl border border-black/10 bg-white px-4 text-sm font-bold outline-none focus:border-black"/>}<input required type="email" placeholder="Email" value={mode==='login'?login.email:reg.email} onChange={e=>mode==='login'?setLogin({...login,email:e.target.value}):setReg({...reg,email:e.target.value})} className="h-14 w-full rounded-2xl border border-black/10 bg-white px-4 text-sm font-bold outline-none focus:border-black"/>{mode==='register'&&<input required placeholder="WhatsApp" value={reg.phone} onChange={e=>setReg({...reg,phone:e.target.value.replace(/\D/g,'')})} className="h-14 w-full rounded-2xl border border-black/10 bg-white px-4 text-sm font-bold outline-none focus:border-black"/>}<input required type="password" placeholder="Password" value={mode==='login'?login.password:reg.password} onChange={e=>mode==='login'?setLogin({...login,password:e.target.value}):setReg({...reg,password:e.target.value})} className="h-14 w-full rounded-2xl border border-black/10 bg-white px-4 text-sm font-bold outline-none focus:border-black"/>{mode==='register'&&<input required type="password" placeholder="Confirm password" value={reg.confirm} onChange={e=>setReg({...reg,confirm:e.target.value})} className="h-14 w-full rounded-2xl border border-black/10 bg-white px-4 text-sm font-bold outline-none focus:border-black"/>}{err&&<p className="rounded-2xl bg-red-50 p-3 text-xs font-bold text-red-600">{err}</p>}<button disabled={busy} className="flex h-14 w-full items-center justify-center rounded-2xl bg-black text-xs font-black uppercase tracking-[.13em] text-white">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:mode==='login'?'Sign in':'Create account'}</button></form>
 </div>;
 const member=user.memberId??user.member_id??user.customer_code??user.code??`MEMBER-${user.id}`;const points=Number(user.points??user.point??user.loyalty_points??0);const tier=user.tier??user.member_tier??'Member';const orders=Number(user.totalOrders??user.total_orders??0);const spent=Number(user.totalSpent??user.total_spent??0);
 return <div className="min-h-full bg-stone-50 px-4 pb-32 pt-7">
  {qr&&<div onClick={()=>setQr(false)} className="fixed inset-0 z-[150] flex items-center justify-center bg-black/70 p-5 backdrop-blur" ><div onClick={e=>e.stopPropagation()} className="w-full max-w-xs rounded-[30px] bg-white p-6 text-center"><QRCodeSVG value={String(member)} className="mx-auto h-52 w-52"/><p className="mt-4 font-mono text-xs font-bold">{member}</p></div></div>}
  <p className="text-[9px] font-black uppercase tracking-[.2em] text-black/30">KALOO member</p><div className="mt-3 rounded-[32px] bg-black p-5 text-white"><div className="flex items-start justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.16em] text-white/35">{tier}</p><h1 className="mt-1 text-3xl font-black tracking-[-.055em]">{user.name||'Member'}</h1><p className="mt-1 text-xs text-white/40">{user.email}</p></div><button onClick={logout} className="flex h-10 w-10 items-center justify-center rounded-full bg-white/10"><LogOut className="h-4 w-4"/></button></div><div className="mt-12 flex items-end justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-white/35">Points</p><p className="mt-1 text-5xl font-black tracking-[-.07em]">{points.toLocaleString('id-ID')}</p></div><button onClick={()=>setQr(true)} className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white text-black"><QrCode/></button></div><p className="mt-6 font-mono text-[10px] text-white/35">{member}</p></div>
  <div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-3xl border border-black/[.07] bg-white p-4"><p className="text-2xl font-black">{orders}</p><p className="mt-1 text-[9px] font-black uppercase tracking-[.13em] text-black/30">Orders</p></div><div className="rounded-3xl border border-black/[.07] bg-white p-4"><p className="truncate text-lg font-black">{new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(spent)}</p><p className="mt-1 text-[9px] font-black uppercase tracking-[.13em] text-black/30">Spent</p></div></div>
  <div className="mt-8 divide-y divide-black/[.07] border-y border-black/[.07]">{[
    ['Order history',History,()=>onViewHistory?onViewHistory():router.push(`${base}/history`)],
    ['My vouchers',Ticket,()=>onViewCoupons?onViewCoupons():router.push(`${base}/coupons`)],
    ['Reservation',CalendarClock,()=>router.push(`${base}/reservation`)]
   ].map(([label,Icon,action]:any)=><button key={label} onClick={action} className="flex w-full items-center gap-4 py-4 text-left"><Icon className="h-4 w-4"/><span className="flex-1 text-sm font-black">{label}</span><ArrowRight className="h-4 w-4 text-black/25"/></button>)}</div>
 </div>;
}
