import { Category, MenuItem } from './types/menu';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Classic Coffee', slug: 'classic-coffee', sortOrder: 1 },
  { id: 'cat-1-mixed', name: 'Mixed Coffee', slug: 'mixed-coffee', sortOrder: 1.5 },
  { id: 'cat-2', name: 'The Morning Bakery', slug: 'the-morning-bakery', sortOrder: 2 },
  { id: 'cat-3', name: 'Savory Mains', slug: 'savory-mains', sortOrder: 3 },
  { id: 'cat-4', name: 'Cold Pressed', slug: 'cold-pressed', sortOrder: 4 },
];

export const MOCK_MENU: MenuItem[] = [
  {
    id: 'item-1',
    categoryId: 'cat-1-mixed',
    name: 'The Artisan Latte',
    description: 'Double shot of house-roasted Ethiopia Yirgacheffe, steamed silky milk, with a trace of forest honey.',
    image: 'https://images.unsplash.com/photo-1461023058943-07cb14c4e548?auto=format&fit=crop&w=800&q=80',
    basePrice: 42000,
    tags: ['best-seller', 'popular'],
    isAvailable: true,
  },
  {
    id: 'item-4',
    categoryId: 'cat-1',
    name: 'The Midnight Pour',
    description: '12-hour Kyoto-style cold drip using single-origin Sumatra beans. Served over a single crystal sphere.',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    basePrice: 55000,
    tags: ['best-seller'],
    isAvailable: true,
  },
  {
    id: 'item-5',
    categoryId: 'cat-1-mixed',
    name: 'Ceremonial Matcha',
    description: 'Stone-ground Uji matcha whisked to a delicate froth with steamed artisanal oat milk.',
    image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=800&q=80',
    basePrice: 48000,
    tags: ['new'],
    isAvailable: true,
  },
  
  // Bakery & Mains remain the same mapping
  {
    id: 'item-2',
    categoryId: 'cat-2',
    name: 'Wildberry Croissant',
    description: '48-hour fermented dough layers, filled with house-made wildberry compote and Madagascan vanilla cream.',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    basePrice: 38000,
    tags: ['new'],
    isAvailable: true,
  },
  {
    id: 'item-6',
    categoryId: 'cat-2',
    name: 'Death by Valrhona',
    description: 'Pain au chocolat featuring three bars of Valrhona 70% dark chocolate and a dusting of fermented cocoa.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    basePrice: 42000,
    tags: ['popular'],
    isAvailable: true,
  },
  {
    id: 'item-7',
    categoryId: 'cat-2',
    name: 'Lemon Myrtle Tart',
    description: 'Shortcrust pastry filled with a zesty lemon curd infused with native Australian lemon myrtle.',
    image: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=800&q=80',
    basePrice: 35000,
    tags: ['new'],
    isAvailable: true,
  },
  {
    id: 'item-8',
    categoryId: 'cat-2',
    name: 'Almond Frangipane',
    description: 'Twice-baked croissant topped with toasted California almonds and a hidden layer of rum-infused almond cream.',
    image: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=800&q=80',
    basePrice: 40000,
    tags: ['popular'],
    isAvailable: true,
  },
  {
    id: 'item-3',
    categoryId: 'cat-3',
    name: 'Truffle Mushroom Pasta',
    description: 'Al dente linguine tossed in a rich truffle cream sauce with roasted wild mushrooms and parmesan reggiano.',
    image: 'https://images.unsplash.com/photo-1473093226795-af9932fe5856?auto=format&fit=crop&w=800&q=80',
    basePrice: 85000,
    tags: ['popular'],
    isAvailable: true,
  },
  {
    id: 'item-9',
    categoryId: 'cat-3',
    name: 'A5 Wagyu Sando',
    description: 'Lightly seared A5 Miyazaki Wagyu, milk bread, and house-made tonkatsu reduction with wasabi mayo.',
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=800&q=80',
    basePrice: 155000,
    tags: ['best-seller'],
    isAvailable: true,
  },
  {
    id: 'item-10',
    categoryId: 'cat-3',
    name: 'Harvest Bowl',
    description: 'Quinoa and kale base topped with maple-roasted roots, tahini lemon drizzle, and toasted pepitas.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    basePrice: 72000,
    tags: ['new'],
    isAvailable: true,
  },
  {
    id: 'item-11',
    categoryId: 'cat-4',
    name: 'The Verdant',
    description: 'Vibrant green juice blend of kale, Granny Smith apple, cucumber, and a sharp ginger kick.',
    image: 'https://images.unsplash.com/photo-1610970881699-44a55b4cfb92?auto=format&fit=crop&w=800&q=80',
    basePrice: 45000,
    tags: ['best-seller'],
    isAvailable: true,
  },
  {
    id: 'item-12',
    categoryId: 'cat-4',
    name: 'Citrus Ember',
    description: 'Zesty blood orange, fresh turmeric root, and black pepper for maximum bioavailability.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80',
    basePrice: 45000,
    tags: ['new'],
    isAvailable: true,
  },
  {
    id: 'item-13',
    categoryId: 'cat-4',
    name: 'Ruby Tonic',
    description: 'Earthy beetroot, pomegranate, and a sprig of rosemary for a deep, sophisticated refreshment.',
    image: 'https://images.unsplash.com/photo-1528498033373-3c6c08e93d79?auto=format&fit=crop&w=800&q=80',
    basePrice: 45000,
    tags: ['popular'],
    isAvailable: true,
  },

  // === CLASSIC COFFEE (Strictly Unique IDs) ===
  {
    id: 'item-cc-1',
    categoryId: 'cat-1',
    name: 'Espresso',
    description: 'A single shot of strong coffee.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    basePrice: 25000,
    isAvailable: true,
  },
  {
    id: 'item-cc-2',
    categoryId: 'cat-1',
    name: 'Doppio',
    description: 'Double shot espresso, more intense.',
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=800&q=80',
    basePrice: 30000,
    isAvailable: true,
  },
  {
    id: 'item-cc-3',
    categoryId: 'cat-1',
    name: 'Americano',
    description: 'Espresso diluted with hot water.',
    image: 'https://images.unsplash.com/photo-1551030173-122aabc4489c?auto=format&fit=crop&w=800&q=80',
    basePrice: 35000,
    isAvailable: true,
  },
  {
    id: 'item-cc-4',
    categoryId: 'cat-1',
    name: 'Cappuccino',
    description: 'Espresso topped with steamed milk and thick foam.',
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80',
    basePrice: 40000,
    isAvailable: true,
  },
  {
    id: 'item-cc-5',
    categoryId: 'cat-1',
    name: 'Caffè Latte',
    description: 'Espresso with more steamed milk, smooth texture.',
    image: 'https://images.unsplash.com/photo-1589395995479-7a3a99268fdf?auto=format&fit=crop&w=800&q=80',
    basePrice: 42000,
    isAvailable: true,
  },
  {
    id: 'item-cc-6',
    categoryId: 'cat-1',
    name: 'Macchiato',
    description: 'Espresso marked with a small amount of milk foam.',
    image: 'https://images.unsplash.com/photo-1557006021-b85faa2bc5e2?auto=format&fit=crop&w=800&q=80',
    basePrice: 38000,
    isAvailable: true,
  },
  {
    id: 'item-cc-7',
    categoryId: 'cat-1',
    name: 'Mocha',
    description: 'Espresso blended with chocolate and milk.',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=800&q=80',
    basePrice: 45000,
    isAvailable: true,
  },
  {
    id: 'item-cc-8',
    categoryId: 'cat-1',
    name: 'Flat White',
    description: 'Similar to latte, but with velvety milk texture.',
    image: 'https://images.unsplash.com/photo-1577968897966-3d41fed6cb54?auto=format&fit=crop&w=800&q=80',
    basePrice: 42000,
    isAvailable: true,
  },
  {
    id: 'item-cc-9',
    categoryId: 'cat-1',
    name: 'Affogato',
    description: 'Espresso poured over vanilla ice cream.',
    image: 'https://images.unsplash.com/photo-1594182903788-b21a8cd3accd?auto=format&fit=crop&w=800&q=80',
    basePrice: 50000,
    isAvailable: true,
  },
  {
    id: 'item-cc-10',
    categoryId: 'cat-1',
    name: 'Cortado',
    description: 'Equal parts espresso and warm milk.',
    image: 'https://images.unsplash.com/photo-1534687941688-1dbdeeedcb42?auto=format&fit=crop&w=800&q=80',
    basePrice: 38000,
    isAvailable: true,
  },
  {
    id: 'item-cc-11',
    categoryId: 'cat-1',
    name: 'Irish Coffee',
    description: 'Coffee mixed with whiskey and whipped cream.',
    image: 'https://images.unsplash.com/photo-1517094038475-b3a62efd4fe9?auto=format&fit=crop&w=800&q=80',
    basePrice: 65000,
    isAvailable: true,
  },
  {
    id: 'item-cc-12',
    categoryId: 'cat-1',
    name: 'Ristretto',
    description: 'A shorter, more concentrated espresso shot.',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
    basePrice: 25000,
    isAvailable: true,
  },
  {
    id: 'item-cc-13',
    categoryId: 'cat-1',
    name: 'Lungo',
    description: 'A longer espresso shot with extra water.',
    image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=800&q=80',
    basePrice: 28000,
    isAvailable: true,
  },
  {
    id: 'item-cc-14',
    categoryId: 'cat-1',
    name: 'Vienna Coffee',
    description: 'Black coffee topped with whipped cream.',
    image: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=800&q=80',
    basePrice: 45000,
    isAvailable: true,
  },
  {
    id: 'item-cc-15',
    categoryId: 'cat-1',
    name: 'Turkish Coffee',
    description: 'Boiled ground coffee, thick and rich.',
    image: 'https://images.unsplash.com/photo-1533591410191-bb27e283b924?auto=format&fit=crop&w=800&q=80',
    basePrice: 35000,
    isAvailable: true,
  },
  {
    id: 'item-cc-16',
    categoryId: 'cat-1',
    name: 'French Press Coffee',
    description: 'Brewed manually with a press, bold flavor.',
    image: 'https://images.unsplash.com/photo-1558913968-d023af7e0344?auto=format&fit=crop&w=800&q=80',
    basePrice: 35000,
    isAvailable: true,
  },
  {
    id: 'item-cc-17',
    categoryId: 'cat-1',
    name: 'Drip Coffee',
    description: 'Classic filter coffee, light and clean taste.',
    image: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=800&q=80',
    basePrice: 30000,
    isAvailable: true,
  },
  {
    id: 'item-cc-18',
    categoryId: 'cat-1',
    name: 'Pour Over',
    description: 'Hand-brewed coffee with paper filter, crisp flavor.',
    image: 'https://images.unsplash.com/photo-1513244304899-73e213bf4bb9?auto=format&fit=crop&w=800&q=80',
    basePrice: 45000,
    isAvailable: true,
  },
  {
    id: 'item-cc-19',
    categoryId: 'cat-1',
    name: 'Syphon Coffee',
    description: 'Brewed with a syphon device, aromatic and theatrical.',
    image: 'https://images.unsplash.com/photo-1618338781987-bf7bf7f87fd0?auto=format&fit=crop&w=800&q=80',
    basePrice: 55000,
    isAvailable: true,
  },
  {
    id: 'item-cc-20',
    categoryId: 'cat-1',
    name: 'Italian Latte',
    description: 'Traditional latte with warm milk.',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    basePrice: 42000,
    isAvailable: true,
  },

  // === MIXED COFFEE (Strictly Unique IDs) ===
  {
    id: 'item-mc-1',
    categoryId: 'cat-1-mixed',
    name: 'Cold Brew',
    description: 'Coffee steeped cold for 12–24 hours.',
    image: 'https://images.unsplash.com/photo-1517701550927-30cfcb64db18?auto=format&fit=crop&w=800&q=80',
    basePrice: 35000,
    isAvailable: true,
  },
  {
    id: 'item-mc-2',
    categoryId: 'cat-1-mixed',
    name: 'Nitro Cold Brew',
    description: 'Cold brew infused with nitrogen, creamy texture.',
    image: 'https://images.unsplash.com/photo-1595928642581-250787e9ec8c?auto=format&fit=crop&w=800&q=80',
    basePrice: 45000,
    isAvailable: true,
  },
  {
    id: 'item-mc-3',
    categoryId: 'cat-1-mixed',
    name: 'Iced Caramel Macchiato',
    description: 'Espresso, cold milk, caramel drizzle.',
    image: 'https://images.unsplash.com/photo-1499961665492-f08cb3ab7460?auto=format&fit=crop&w=800&q=80',
    basePrice: 55000,
    isAvailable: true,
  },
  {
    id: 'item-mc-4',
    categoryId: 'cat-1-mixed',
    name: 'Vanilla Sweet Cream Cold Brew',
    description: 'Cold brew topped with vanilla cream.',
    image: 'https://images.unsplash.com/photo-1559525839-b184a4d698c7?auto=format&fit=crop&w=800&q=80',
    basePrice: 50000,
    isAvailable: true,
  },
  {
    id: 'item-mc-5',
    categoryId: 'cat-1-mixed',
    name: 'Spanish Latte',
    description: 'Espresso with milk and condensed sweetener.',
    image: 'https://images.unsplash.com/photo-1588661642875-6850c93cd5dc?auto=format&fit=crop&w=800&q=80',
    basePrice: 45000,
    isAvailable: true,
  },
  {
    id: 'item-mc-6',
    categoryId: 'cat-1-mixed',
    name: 'Palm Sugar Milk Coffee',
    description: 'Espresso with milk and Indonesian palm sugar.',
    image: 'https://images.unsplash.com/photo-1578314545931-15b746197fa3?auto=format&fit=crop&w=800&q=80',
    basePrice: 28000,
    isAvailable: true,
  },
  {
    id: 'item-mc-7',
    categoryId: 'cat-1-mixed',
    name: 'Dirty Matcha Latte',
    description: 'Matcha green tea with an espresso shot.',
    image: 'https://images.unsplash.com/photo-1536816579748-4ecb3f03d72a?auto=format&fit=crop&w=800&q=80',
    basePrice: 55000,
    isAvailable: true,
  },
  {
    id: 'item-mc-8',
    categoryId: 'cat-1-mixed',
    name: 'Pumpkin Spice Latte',
    description: 'Latte flavored with pumpkin spice blend.',
    image: 'https://images.unsplash.com/photo-1505364124376-7788b14a2fc1?auto=format&fit=crop&w=800&q=80',
    basePrice: 58000,
    isAvailable: true,
  },
  {
    id: 'item-mc-9',
    categoryId: 'cat-1-mixed',
    name: 'Salted Caramel Latte',
    description: 'Latte with caramel and a hint of sea salt.',
    image: 'https://images.unsplash.com/photo-1620916297397-a4a54199187a?auto=format&fit=crop&w=800&q=80',
    basePrice: 55000,
    isAvailable: true,
  },
  {
    id: 'item-mc-10',
    categoryId: 'cat-1-mixed',
    name: 'Tiramisu Latte',
    description: 'Latte inspired by tiramisu dessert flavors.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6fba?auto=format&fit=crop&w=800&q=80',
    basePrice: 60000,
    isAvailable: true,
  },
  {
    id: 'item-mc-11',
    categoryId: 'cat-1-mixed',
    name: 'Honey Cinnamon Latte',
    description: 'Latte sweetened with honey and spiced with cinnamon.',
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=800&q=80',
    basePrice: 52000,
    isAvailable: true,
  },
  {
    id: 'item-mc-12',
    categoryId: 'cat-1-mixed',
    name: 'Coconut Latte',
    description: 'Latte made with coconut milk.',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80',
    basePrice: 48000,
    isAvailable: true,
  },
  {
    id: 'item-mc-13',
    categoryId: 'cat-1-mixed',
    name: 'Rose Latte',
    description: 'Latte infused with rose syrup.',
    image: 'https://images.unsplash.com/photo-1578314674062-811cff721b06?auto=format&fit=crop&w=800&q=80',
    basePrice: 55000,
    isAvailable: true,
  },
  {
    id: 'item-mc-14',
    categoryId: 'cat-1-mixed',
    name: 'Lavender Latte',
    description: 'Latte with floral lavender notes.',
    image: 'https://images.unsplash.com/photo-1553956105-091a084c04f9?auto=format&fit=crop&w=800&q=80',
    basePrice: 55000,
    isAvailable: true,
  },
  {
    id: 'item-mc-15',
    categoryId: 'cat-1-mixed',
    name: 'Charcoal Latte',
    description: 'Latte with activated charcoal, striking look.',
    image: 'https://images.unsplash.com/photo-1510972527921-ce6c2a417932?auto=format&fit=crop&w=800&q=80',
    basePrice: 48000,
    isAvailable: true,
  },
  {
    id: 'item-mc-16',
    categoryId: 'cat-1-mixed',
    name: 'Oat Milk Latte',
    description: 'Latte with oat milk, vegan-friendly.',
    image: 'https://images.unsplash.com/photo-1625805562723-5eac1b88e1bb?auto=format&fit=crop&w=800&q=80',
    basePrice: 52000,
    isAvailable: true,
  },
  {
    id: 'item-mc-17',
    categoryId: 'cat-1-mixed',
    name: 'Hazelnut Mocha',
    description: 'Mocha enhanced with hazelnut syrup.',
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=800&q=80',
    basePrice: 55000,
    isAvailable: true,
  },
  {
    id: 'item-mc-18',
    categoryId: 'cat-1-mixed',
    name: 'Banana Coffee Smoothie',
    description: 'Espresso blended with banana and milk.',
    image: 'https://images.unsplash.com/photo-1536643265535-1875156a5c1e?auto=format&fit=crop&w=800&q=80',
    basePrice: 45000,
    isAvailable: true,
  },
  {
    id: 'item-mc-19',
    categoryId: 'cat-1-mixed',
    name: 'Avocado Coffee',
    description: 'Coffee mixed with avocado and condensed milk.',
    image: 'https://images.unsplash.com/photo-1598918257088-ff814cc5a2ff?auto=format&fit=crop&w=800&q=80',
    basePrice: 42000,
    isAvailable: true,
  },
  {
    id: 'item-mc-20',
    categoryId: 'cat-1-mixed',
    name: 'Regal Biscuit Iced Coffee',
    description: 'Iced milk coffee served with Regal biscuits.',
    image: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
    basePrice: 35000,
    isAvailable: true,
  }
].map(item => {
  const isCold = item.name.toLowerCase().includes('iced') || item.name.toLowerCase().includes('cold') || item.name.toLowerCase().includes('smoothie') || item.categoryId === 'cat-1-mixed';
  return {
    ...item,
    meta: {
      schema_version: "1.0",
      sku_code: `SKU-${item.id.toUpperCase()}`,
      category: item.categoryId === 'cat-1' ? 'Classic Coffee' : (item.categoryId === 'cat-1-mixed' ? 'Mixed Coffee' : 'Food/Bakery'),
      short_description: item.description,
      flavor_profile: "Balanced, nuanced, and structurally complex.",
      strength: isCold ? "Medium" : "Strong",
      serve_temperature: isCold ? "cold" : "hot",
      sizes: [
        { label: "Regular", volume_ml: 250, price: item.basePrice },
        { label: "Large", volume_ml: 350, price: Math.round(item.basePrice * 1.2 / 1000) * 1000 }
      ],
      add_ons: [
        { id: "ao-shot", name: "Extra Espresso Shot", price: 8000, type: "shots" },
        { id: "ao-syrp-vanilla", name: "Vanilla Syrup", price: 6000, type: "syrup" },
        { id: "ao-syrp-caramel", name: "Caramel Syrup", price: 6000, type: "syrup" },
        { id: "ao-milk-oat", name: "Oat Milk Swap", price: 12000, type: "milk" },
        { id: "ao-milk-almond", name: "Almond Milk Swap", price: 12000, type: "milk" },
        { id: "ao-sweet-less", name: "Less Sweet", price: 0, type: "sweetness" },
        { id: "ao-sweet-normal", name: "Normal Sweet", price: 0, type: "sweetness" },
        { id: "ao-temp-hot", name: "Serve Hot", price: 0, type: "temperature" },
        { id: "ao-temp-ice", name: "Serve Iced", price: 0, type: "temperature" },
      ],
      allergens: ["dairy", "caffeine"],
      barista_recipe: {
        coffee_origin_or_blend: "Ethiopia Yirgacheffe & Colombia Supremo Blend",
        roast_level: "Medium Light",
        dose_grams: 18.5,
        yield_ml: 38,
        extraction_time_seconds: 28,
        milk_type: "Standard Whole Milk",
        milk_volume_ml: 150,
        steam_temperature_celsius: 65,
        syrup_pumps_per_size: { "Regular": 1, "Large": 2 },
        presentation_notes: "Serve with latte art or clear ice sphere. Ensure glass is chilled."
      },
      prep_time_estimate_seconds: 120,
      recommended_pairings: ["item-2", "item-6"]
    }
  } as MenuItem;
});
